name: List

on:
  push:
  pull_request:

env:
  START_INDEX: 200
  COUNT_INDEX: 150

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    # Checkout
    - name: Checkout
      uses: actions/checkout@v4

    # Setup environment
    - name: Setup environment
      run: |
        sudo apt-get update
        mkdir -p list

    # Install dependencies
    - name: Install dependencies
      run: |
        sudo apt install 7zip
        wget -q "https://github.com/encounter/decomp-toolkit/releases/download/v1.5.1/dtk-linux-x86_64"
        mv dtk* dtk
        chmod +x dtk

    # List files
    - name: List files
      run: |
        baselnk="https://myrient.erista.me/files/Redump/Nintendo%20-%20Wii%20-%20NKit%20RVZ%20[zstd-19-128k]"
        
        declare -i start=$START_INDEX
        declare -i count=$COUNT_INDEX
        declare -i index=0
        
        start=$(( start - 1 ))
        count=$(( count + start ))
        count=$(( count + 1 ))
        while read line; do
            if (( index > start )); then
                if (( index < count )); then
                    if ! test -f "list/$line.txt"; then
                        gamelnk="$baselnk/$line.zip"
                        gamezip="$line.zip"
                        gamedisc="$line.rvz"
                        echo -e "$line"
                        echo -e "     Download"
                        wget -q "$gamelnk"
                        echo -e "     Extract"
                        7z x "$gamezip" -y -bso0 -bsp0 -bse0
                        rm -rf "$gamezip"
                        echo -e "     List"
                        ./dtk vfs ls -r "$gamedisc:files" > "list/$line.txt"
                        rm -rf "$gamedisc"
                    fi
                fi
            fi
            index=$(( index + 1 ))
        done <list.txt
        7z a DVDFSList.7z ./list/*
        rm -rf dtk

    # Upload list
    - name: Upload list
      uses: actions/upload-artifact@v4
      with:
        name: DVDFSList
        path: DVDFSList.7z
