name: List

on:
  push:
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    # Checkout
    - name: Checkout
      uses: actions/checkout@v4

    # Setup environment
    - name: Setup environment
      run: |
        sudo apt-get update
        mkdir -p list

    # Install dependencies
    - name: Install dependencies
      run: |
        sudo apt install 7zip
        wget -q "https://github.com/encounter/decomp-toolkit/releases/download/v1.5.1/dtk-linux-x86_64"
        mv dtk* dtk
        chmod +x dtk

    # List files
    - name: List files
      run: |
        bash getfileexts.sh
        rm -rf dtk
        7z a DVDFSData.7z ./*

    # Upload list
    - name: Upload list
      uses: actions/upload-artifact@v4
      with:
        name: DVDFSList
        path: DVDFSList.7z
